services:
  seanime:
    image: umagistr/seanime:latest
    container_name: seanime
    environment:
      - QBIT_WEBUI_PORT=8081
      - QBIT_USERNAME=admin
      - QBIT_PASSWORD=adminadmin
    ports:
      - "3211:43211"
      - "8081:8081" # qBittorrent WebUI
    volumes:
      - ./config:/root/.config
      - ./anime:/anime
      - ./downloads:/downloads
    restart: unless-stopped
